server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.cloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/*Mapper.xml
  
spring:
  application:
    name: Atguigu-SCMS-Dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_db_one?characterEncoding=utf8
    username: root
    password: huishan123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
eureka:
  client:
    service-url:
#      单测
      defaultZone: http://localhost:7000/eureka
#      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka